#!/bin/bash
set -o nounset

# die MESSAGE 
function die {
   if [ -n "$1" ]; then
      echo "$1" <&2
   else
      echo "Unexpected error. Exiting."<&2
   fi
   exit 1
}

#------------------------------------------------------------------------------------
# PASS=? dr_compress SOURCEFOLDER ARCHIVEFOLDER ARCHIVENAME

if [ $# -ne 3 ]; then die "PASS=? dr_compress SOURCEFOLDER ARCHIVEFOLDER ARCHIVENAME" ; fi

SOURCEFOLDER=$(realpath "$1" | tr -d '\r\n')
if [ $? -ne 0 ]; then die "dr_compress: Couldn't find source path ${1}." ; fi

ARCHIVEFOLDER=$(realpath "$2" | tr -d '\r\n')
if [ $? -ne 0 ]; then die "dr_compress: Couldn't find destination path ${2}." ; fi

ARCHIVEPATH="$ARCHIVEFOLDER/$3"

# default to empty string if doesn't exist, then test for empty string.
if [ -n "${PASS-}" ]; then 
   PASSCMD="-p${PASS}"; 
else
   PASSCMD=""
   echo "WARNING: No password supplied. Backup is not encrypted!">&2
fi

tar cf - -C "$SOURCEFOLDER" . | 7za a -si "${PASSCMD}" "$ARCHIVEPATH" > /dev/null
if [ $? -ne 0 ]; then die "Failed to create archive of $SOURCEFOLDER" ; fi

