#!/bin/bash
set -o nounset

readonly COPYIMAGE="j842/dr-baseimage-alpine"

# die MESSAGE 
function die {
   if [ -n "$1" ]; then
      echo "$1" <&2
   else
      echo "Unexpected error. Exiting."<&2
   fi
   exit 1
}

# dr_decompressvolume VOLUMENAME ARCHIVEFOLDER ARCHIVENAME

if [ $# -ne 3 ]; then die "dr_decompressvolume VOLUMENAME ARCHIVEFOLDER ARCHIVENAME" ; fi

VOLUMENAME="$1"
ARCHIVEFOLDER=$(realpath "$2" | tr -d '\r\n')
ARCHIVENAME="$3"
if [ ! -e "$ARCHIVEFOLDER/$ARCHIVENAME" ]; then die "dr_decompressvolume: Couldn't find archive $ARCHIVENAME" ; fi

DCNAME="dr-decompressvolume"

# destroy any pre-existing data!
docker volume rm "${VOLUMENAME}" >/dev/null
docker volume create --name="${VOLUMENAME}" >/dev/null
docker run --name="${DCNAME}" \
   -v "${VOLUMENAME}:/vol" -v "${ARCHIVEFOLDER}:/archive" "${COPYIMAGE}" \
   /bin/bash -c "tar zxf /archive/${ARCHIVENAME} -C /vol"
docker rm "${DCNAME}" >/dev/null 

