#!/bin/bash
set -o nounset
set -e

# ██╗   ██╗ █████╗ ██╗     ██╗██████╗  █████╗ ████████╗ ██████╗ ██████╗ 
# ██║   ██║██╔══██╗██║     ██║██╔══██╗██╔══██╗╚══██╔══╝██╔═══██╗██╔══██╗
# ██║   ██║███████║██║     ██║██║  ██║███████║   ██║   ██║   ██║██████╔╝
# ╚██╗ ██╔╝██╔══██║██║     ██║██║  ██║██╔══██║   ██║   ██║   ██║██╔══██╗
#  ╚████╔╝ ██║  ██║███████╗██║██████╔╝██║  ██║   ██║   ╚██████╔╝██║  ██║
#   ╚═══╝  ╚═╝  ╚═╝╚══════╝╚═╝╚═════╝ ╚═╝  ╚═╝   ╚═╝    ╚═════╝ ╚═╝  ╚═╝
 
 
# check that drunner itself is installed okay.
 
                                                                      
readonly CODE_S="\e[32m"
readonly CODE_E="\e[0m"

# die MESSAGE 
function die {
   echo -e " ">&2
   echo -e "\e[31m\e[1mInstallation broken. ${1}\e[0m">&2
   echo -e " ">&2
   echo -e "Download the latest drunner-install and run it.">&2
   echo -e "Your services and data will be preserved.">&2
   echo -e " ">&2
   echo -e "${CODE_S}https://raw.github.com/j842/dockerrunner/master/drunner-install${CODE_E}">&2
   echo -e " ">&2
   exit 1
}

# Validate drunner is installed okay
if [ -e "/etc/drunner/drunner.cfg" ]; then die "You have an old installation of drunner. Try copying drunner.cfg to config.sh in /etc/drunner, then drunner update"
if [ ! -e "/etc/drunner/config.sh" ]; then die "/etc/drunner/config.sh missing." ; fi
source "/etc/drunner/config.sh"
if [ ! -v ROOTPATH ]; then die "config.sh doesn't set ROOTPATH."; fi
if [ ! -v PULLONUPDATE ]; then die "config.sh doesn't set PULLONUPDATE."; fi
if [ ! -v SUPPORTIMAGE ]; then die "config.sh doesn't set SUPPORTIMAGE."; fi
if [ ! -v DRUNNERINSTALLURL ]; then die "config.sh doesn't set DRUNNERINSTALLURL."; fi
if [ ! -v DRUNNERINSTALLTIME ]; then die "config.sh doesn't set DRUNNERINSTALLTIME."; fi

if [ ! -d "$ROOTPATH" ]; then die "$ROOTPATH doesn't exist."; fi

if [ ! -e "${ROOTPATH}/support/buildtime.sh" ]; then die "${ROOTPATH}/support/buildtime.sh is missing." ; fi
source "${ROOTPATH}/support/buildtime.sh"
if [ ! -v SUPPORTBUILDTIME ]; then die "buildtime.sh doesn't set SUPPORTBUILDTIME." ; fi

exit 0
