#!/bin/bash
set -o nounset
set -e

# ██╗   ██╗ █████╗ ██╗     ██╗██████╗  █████╗ ████████╗ ██████╗ ██████╗ 
# ██║   ██║██╔══██╗██║     ██║██╔══██╗██╔══██╗╚══██╔══╝██╔═══██╗██╔══██╗
# ██║   ██║███████║██║     ██║██║  ██║███████║   ██║   ██║   ██║██████╔╝
# ╚██╗ ██╔╝██╔══██║██║     ██║██║  ██║██╔══██║   ██║   ██║   ██║██╔══██╗
#  ╚████╔╝ ██║  ██║███████╗██║██████╔╝██║  ██║   ██║   ╚██████╔╝██║  ██║
#   ╚═══╝  ╚═╝  ╚═╝╚══════╝╚═╝╚═════╝ ╚═╝  ╚═╝   ╚═╝    ╚═════╝ ╚═╝  ╚═╝
 
 
# check that drunner itself is installed okay.
 
                                                                      
readonly CODE_S="\e[32m"
readonly CODE_E="\e[0m"

# die MESSAGE 
function die {
   echo -e " ">&2
   echo -e "\e[31m\e[1mInstallation broken. ${1}\e[0m">&2
   echo -e " ">&2
   echo -e "Download the latest drunner-install and run it.">&2
   echo -e "Your services and data will be preserved.">&2
   echo -e " ">&2
   echo -e "${CODE_S}https://raw.github.com/j842/dockerrunner/master/drunner-install${CODE_E}">&2
   echo -e " ">&2
   exit 1
}

# Validate drunner is installed okay
[ ! -e "/etc/drunner/drunner.cfg" ] || die "You have an old installation of drunner. Try moving drunner.cfg to config.sh in /etc/drunner, then drunner update"
[ -e "/etc/drunner/config.sh" ] || die "/etc/drunner/config.sh missing."

source "/etc/drunner/config.sh"

[ -v ROOTPATH ]            || die "config.sh doesn't set ROOTPATH."
[ -v PULLONUPDATE ]        || die "config.sh doesn't set PULLONUPDATE."
[ -v SUPPORTIMAGE ]        || die "config.sh doesn't set SUPPORTIMAGE."
[ -v DRUNNERINSTALLURL ]   || die "config.sh doesn't set DRUNNERINSTALLURL."
[ -v DRUNNERINSTALLTIME ]  || die "config.sh doesn't set DRUNNERINSTALLTIME."
[ -d "$ROOTPATH" ]         || die "$ROOTPATH doesn't exist."

[ -e "${ROOTPATH}/support/buildtime.sh" ] || die "${ROOTPATH}/support/buildtime.sh is missing."

source "${ROOTPATH}/support/buildtime.sh"

[ -v SUPPORTBUILDTIME ]    || die "buildtime.sh doesn't set SUPPORTBUILDTIME." 

exit 0
