#!/bin/bash

IMAGENAME="drunner/support"


#------------------------------------------------

BRANCH=$(git rev-parse --abbrev-ref HEAD)

if [ "$BRANCH" = "master" ]; then
  TAG=""
else
  TAG=":${BRANCH}"
fi

TARGET="${IMAGENAME}/support${TAG}"

docker build -t "$TARGET" .

echo " "
echo "Built $TARGET"
