#!/bin/bash
set -o nounset

#  ██████╗ ██████╗ ███╗   ███╗██████╗ ██████╗ ███████╗███████╗███████╗
# ██╔════╝██╔═══██╗████╗ ████║██╔══██╗██╔══██╗██╔════╝██╔════╝██╔════╝
# ██║     ██║   ██║██╔████╔██║██████╔╝██████╔╝█████╗  ███████╗███████╗
# ██║     ██║   ██║██║╚██╔╝██║██╔═══╝ ██╔══██╗██╔══╝  ╚════██║╚════██║
# ╚██████╗╚██████╔╝██║ ╚═╝ ██║██║     ██║  ██║███████╗███████║███████║
#  ╚═════╝ ╚═════╝ ╚═╝     ╚═╝╚═╝     ╚═╝  ╚═╝╚══════╝╚══════╝╚══════╝
                                                                                                                                                   

# die MESSAGE 
function die {
   if [ "$#" -eq 1 ]; then
      echo "$1" <&2
   else
      echo "Unexpected error. Exiting."<&2
   fi
   exit 1
}

function volexists {
  docker volume ls | grep "$1" > /dev/null
}

#------------------------------------------------------------------------------------
# PASS=? compress SOURCEPATH/VOLUME ARCHIVEFOLDER ARCHIVENAME

if [ $# -ne 3 ]; then die "PASS=? compress SOURCEPATH/VOLUME ARCHIVEFOLDER ARCHIVENAME" ; fi

if [ -d "$1" ]; then
   # path
   SOURCE=$(realpath "$1" | tr -d '\r\n')
   if [ $? -ne 0 ]; then die "compress: Couldn't find source path ${1}." ; fi
else
   # volume
   volexists "$1"
   if [ $? -ne 0 ]; then die "$1 is not a valid path nor Docker volume container." ; fi   
   SOURCE="$1"
fi

ARCHIVEFOLDER=$(realpath "$2" | tr -d '\r\n')
if [ $? -ne 0 ]; then die "compress: Couldn't find destination path ${2}." ; fi

ARCHIVENAME="$3"

TEMPDIR="$(mktemp -d)"
chmod a+rwx "${TEMPDIR}"

docker run -i -t --name="dr_compress" -e "PASS=${PASS}" \
            -v "${SOURCE}:/src" -v "${TEMPDIR}:/dst" \
            j842/dr-support dr_compress "${ARCHIVENAME}"
RVAL=$?
docker rm "dr_compress" >/dev/null 2>&1

if [ "$RVAL" -eq 0 ]; then
   mv "${TEMPDIR}/${ARCHIVENAME}" "${ARCHIVEFOLDER}"
   RVAL=$?
fi
rm -r "${TEMPDIR}"

exit "$RVAL"

