#!/bin/bash
set -o nounset
set -e

# ██╗   ██╗ █████╗ ██╗     ██╗██████╗  █████╗ ████████╗ ██████╗ ██████╗ 
# ██║   ██║██╔══██╗██║     ██║██╔══██╗██╔══██╗╚══██╔══╝██╔═══██╗██╔══██╗
# ██║   ██║███████║██║     ██║██║  ██║███████║   ██║   ██║   ██║██████╔╝
# ╚██╗ ██╔╝██╔══██║██║     ██║██║  ██║██╔══██║   ██║   ██║   ██║██╔══██╗
#  ╚████╔╝ ██║  ██║███████╗██║██████╔╝██║  ██║   ██║   ╚██████╔╝██║  ██║
#   ╚═══╝  ╚═╝  ╚═╝╚══════╝╚═╝╚═════╝ ╚═╝  ╚═╝   ╚═╝    ╚═════╝ ╚═╝  ╚═╝
                                                                      

# Validate the image I'm running in as being Docker Runner compatible
# Gets copied to the host as part of installing dr-support, then mounted
# in the other container by dr to run the check.

function die {
   echo "Not Docker Runner compatible - $1">&2
   exit 1   
}

if [ "$UID" -eq 0 ]; then 
   die "the container runs as root." 
fi

# Check mandatory files in image (global var IMAGENAME) before touching host. Is it a valid dr container?
readonly REQDFILES=("install" "destroy" "backup" "restore" "help" "enter" "volumes")
for CFILE in "${REQDFILES[@]}"; do
   if [ ! -e "/dr/$CFILE" ]; then
      die "required file not present: /dr/$CFILE"
   fi
done

source /dr/volumes
if [ ! -v VOLUMES ]; then die "volumes file did not define variable VOLUMES"; fi

exit 0


