#!/bin/bash
set -o nounset

# die MESSAGE 
function die {
   if [ -n "$1" ]; then
      echo "$1" <&2
   else
      echo "Unexpected error. Exiting."<&2
   fi
   exit 1
}

#------------------------------------------------------------------------------------
# PASS=? dr_decompress ARCHIVENAME

if [ "$#" -ne 1 ]; then die "PASS=? dr_decompress ARCHIVENAME" ; fi

DESTFOLDER="/dst"
ARCHIVEPATH="/src/$1"

if [ ! -e "$ARCHIVEPATH" ]; then die "dr_decompress: No such archive: $ARCHIVEPATH"; fi
if [ ! -d "$DESTFOLDER" ]; then die "dr_decompress: Destination folder does not exist: $DESTFOLDER"; fi
 
# default to empty string if doesn't exist, then test for empty string.
if [ -n "${PASS-}" ]; then 
   PASSCMD="-p${PASS}"; 
else
   PASSCMD=""
   echo "WARNING: No password supplied.">&2
fi

7za x -so "${PASSCMD}" "${ARCHIVEPATH}" | tar xf - -C "${DESTFOLDER}"
if [ $? -ne 0 ]; then die "Failed to decompress archive. The password may be incorrect!"; fi
