#!/bin/bash

# get-drunner-install PATH URL



if [ "$#" -ne 2 ]; then 
   echo "get-dr-install: wrong number of args.">&2
   exit 1
fi

TARGETDIR="$1"
DOWNLOADURL="$2"

if [ ! -d "${TARGETDIR}" ]; then
   echo "get-dr-install: Directory ${TARGETDIR} does not exist.">&2
   exit 1
fi

TARGET="${TARGETDIR}/drunner-install"

if [ -e "${TARGET}" ]; then
   rm "${TARGET}"
   if [ $? -ne 0 ]; then
      echo "get-dr-install: ${TARGET} already exists and couldn't be removed.">&2
      exit 1
   fi
fi

wget --no-cache -nv -O "${TARGET}" "${DOWNLOADURL}"

if [ ! -e "${TARGET}" ]; then 
   echo "get-dr-install: Download failed!">&2
   exit 1
fi

exit 0
